server:
  port: 8000

spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3361}/${DB_NAME:customer_ms_db}
    username: root
    password: ${DB_PASS:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import: ${CONFIG_HOST:optional:configserver:http://localhost:8070/}
    profiles:
      active: ${SPRING_PROFILES_ACTIVE:default}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

endpoints:
  shoutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8071/eureka/}

info:
  app:
    name: "Customer"
    description: "Customer system"
    version: "1.0.0"